name: ci
on:
  push:
    branches: [main, 'feature/**']
  pull_request:
    branches: [main]

jobs:
  build:
    name: unit-test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - name: Run cargo test
      run: cargo test
    - name: Run tarpaulin
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.15.0'
        args: '-- --test-threads 1'
    - name: Upload to codecov.io
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v2
    - name: Archive code coverage results
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
      
      
