name: ci
on:
  push:
    branches: [main, 'feature/**']
  pull_request:
    branches: [main]

jobs:
  build:
    name: unit-test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - name: Run cargo test
      run: cargo test
    - name: Coverage
      if: ${{matrix.os == ubuntu-latest}}
      run: cargo install cargo-kcov
      
      
